const translation = {
    en: {
        night: 'Good night',
        morning: 'Good morning',
        afternoon: 'Good afternoon',
        evening: 'Good evening',
        placeholder: '[Enter name]',
        localDate: 'en-US',
        city: 'Minsk',
        wind: 'Wind speed',
        humidity: 'Humidity',
        language: 'language',
        time: 'time',
        date: 'date',
        greeting: 'greeting',
        quotes: 'quotes',
        weather: 'weather',
        background: 'background',
        russian: 'russian',
        english: 'english',
        speed: 'm/s',
        error: 'Error! City not found for',
        player: 'audio-player',
        tag: 'tag',
    },
    ru: {
        night: 'Доброй ночи',
        morning: 'Доброе утро',
        afternoon: 'Добрый день',
        evening: 'Добрый вечер',
        placeholder: '[Введите имя]',
        localDate: 'ru',
        city: 'Минск',
        wind: 'Скорость ветра',
        humidity: 'Влажность',
        language: 'язык',
        time: 'время',
        date: 'дата',
        greeting: 'приветствие',
        quotes: 'цитаты',
        weather: 'погода',
        background: 'фон',
        russian: 'русский',
        english: 'английский',
        speed: 'м/с',
        error: 'Ошибка! Город не найден для',
        player: 'аудиоплеер',
        tag: 'тема',
    }
};

export default translation;

